### ISSUE TITLE
Bitrate of 100K?

### ISSUE THREAD

**Issue by maxkr2** [exothink/eXoCAN#14]
Great work, thank you! Can you please tell me what has to be modifed for a bitrate of 100K? I have an already existing system I want to connect to. And is it possible to use CAN at PB8+9 and also PA11+12 via USB on "BluePill" for a serial output at the same time?

Regards,
Max

**Comment by exothink** [comment]
see 103 docs for bit rates
see closed "Init with USB or CAN"
