### ISSUE TITLE
SN65HVD230 support

### ISSUE THREAD

**Issue by mdvorak** [exothink/eXoCAN#21]
Even thou I'm not user of this library, I've came across it while searching why my SN65HVD230 does not work. I have the same cheap knock-off from Ali.
Problem was 10 kΩ resistor, tying Rs (8) pin to ground, while the Rs should be tied to the ground directly.

From datasheet:

> The RS pin (pin 8) on the SN65HVD230 and SN65HVD231 provides three different modes of operation: high
speed mode, slope control mode, and low-power mode. The high speed mode of operation is selected by
connecting the RS pin to ground, allowing the transmitter output transistors to switch on and off as fast as
possible with no limitation on the rise and fall slopes. The rise and fall slopes can also be adjusted by connecting
a resistor in series between the RS pin and ground. The slope will be proportional to the pin's output current. With
a resistor value of 10 kΩ the device will have a slew rate of ~15 V/μs, and with a resistor value of 100 kΩ the
device will have a slew rate of ~2 V/μs. 

**Solution:** Remove 10 kΩ resistor (R1 on my module), and connect it directly (0 Ω resistor, piece of wire or good amount of solder will do). This puts chip in the high performance mode, and viola, it started to work.

If you want, you can do a test.

**Comment by exothink** [comment]
Great info. Tks.
