### ISSUE TITLE
Filter with extend mask

### ISSUE THREAD

**Issue by spectrum98** [exothink/eXoCAN#5]
I can't get the extended id and filtering to work.
Example: 

can.filterMask32Init (0, 0x00232461,0x1FFFFFFF);
using eXoCAN can(EXT_ID_LEN, BR1M, PORTA_11_12_WIRE_PULLUP);

it should filter everything except 0x232461 ... but it doesn't work as expected. Nothing is received, 0x232461 is filtered.

**Comment by exothink** [comment]
You are correct.  I am working on a solution.
