### ISSUE TITLE
Using 2 CAN buses simultaneous

### ISSUE THREAD

**Issue by sundar19** [exothink/eXoCAN#7]
I saw that there are 2 can buses within the bluepill. Is it possible for me to initialize and use both of them simultaneously ?

**Comment by exothink** [comment]
No. The 103 only has one full CAN Bus.

**Comment by sundar19** [comment]
Thank you so much

**Comment by exothink** [comment]
Try Teensy.  They have multi CAN buses.

**Comment by sundar19** [comment]
Hi thank you so much for suggestion , I got this doubt since PA11 & PA12 as well as PB8 & PB9 both are specified as CAN bus ports(I am using TJA1050 transceiver based CAN). Thank you so much for this library!
