### ISSUE TITLE
USB Serial not working after upload 

### ISSUE THREAD

**Issue by PePeLLee** [exothink/eXoCAN#8]
Until now I was using mcp 2515 for CAN transmission. I wanted to give a try to mcp2551 as blue pill has built in support of CAN.
Manged to add your library to Arduino IDE and uploaded example sketch. 
After uploading I don't have usb serial any more.
Is it possible to have CAN and usb serial at same time?
I have tried both PORTA_11_12_WIRE_PULLUP and PORTB_8_9_WIRE_PULLUP. Nothing helps. 
When I upload any other sketch usb works fine.

Arduino IDE: 1.8.13
Board core: 
https://github.com/stm32duino/BoardManagerFiles/raw/master/package_stmicroelectronics_index.json

**Comment by exothink** [comment]
The stm32f103 shares hardware between the USB serial and CAN.  It isn't possible to have them both work at the same time.  You can use CAN and a serial port with an external serial to USB adapter instead.
